### ISSUE TITLE
Java 16 guide is confusing after Java 17 release

### ISSUE THREAD

**Issue by TwoLeggedCat** [PaperMC/PaperDocs#114]
https://paper.readthedocs.io/en/latest/java-update/index.html#windows-10 has the user visit https://adoptium.net/?variant=openjdk16&jvmVariant=hotspot, which, while working, at least for the moment, is confusing as there is no longer a bubble for Java 16 so it looks as though they need to select a version.

I'm not sure if it would be better to update the guide to use a direct link to the msi file, or change the entire thing to be about upgrading to Java 17.

**Comment by Chew** [comment]
We _could_ redirect them to 17, there's also https://adoptium.net/releases.html?variant=openjdk16&jvmVariant=hotspot which has the bubble still.

I would assume Java 17 is not only working but preferred since there weren't any major changes.

**Comment by TwoLeggedCat** [comment]
Well, there was the removal of `--illegal-access=permit`, which some servers still rely on 🤮
I agree changing it to 17 would be better, although I think the best solution would be to make it a guide on updating to whatever the latest version is, which would be useful if Mojang decides to keep bumping the Java version every release.

**Comment by NotMyFault** [comment]
@sulu5890 Please close, looks like I referenced this issue too early.

**Comment by TwoLeggedCat** [comment]
I guess titles don't count
