### ISSUE TITLE
paperweight userdev

### ISSUE THREAD

**Issue by electronicboy** [PaperMC/PaperDocs#125]
We routinely see people asking for support with nms for paper, which ofc is generally satisfied by linking to jmp's test plugin repo, this works for people who are somewhat familiar with gradle or are capable of a bowl of copypasta, there's no real documentation available in how to use it bar the example

While this works for onboarding most, there's little in the way of explaining the "implications" as such of it, e.g. proper documentation over how to add it, as well as the somewhat common issue recently where when the data version is updated, people are generally confused by its meaning and there's no real documentation over what to do

**Comment by e-im** [comment]
merged with https://github.com/PaperMC/docs/issues/19
