### ISSUE TITLE
[Suggestion] Update ReadTheDocs to reflect paper.yml

### ISSUE THREAD

**Issue by ShaneBeee** [PaperMC/PaperDocs#20]
I just wanted to suggest updating the [read the docs](https://paper.readthedocs.org/ ) site to reflect the async chunk loading stuff from the paper.yml

I understand to some (or most) this may be considered "self explanatory" but to some of us, we don't fully understand async, or async chunk loading, and having a clearer explanation of it documented on that site would help give us a better understanding of how it works, and its benefits.

Thank you for reading!

**Comment by xParadoxical69** [comment]
http://lmgtfy.com/?q=what+does+mean+async

**Comment by ShaneBeee** [comment]
ha... ha.... ha.... very funny.
The point I was making is theres things in the config some people may not know about, and the documents page should be updated to reflect!

**Comment by xParadoxical69** [comment]
Yeah, I agree, it should be updated. Docs still are missing some of the new config options.

@zachbr

**Comment by zachbr** [comment]
PRs welcome.

**Comment by aikar** [comment]
Well that config specifically is don't touch unless one of us tells you to
