### ISSUE TITLE
Downloads API still up-to-date?

### ISSUE THREAD

**Issue by MichaIng** [PaperMC/PaperDocs#47]
In the docs, API v1 is explained: https://paper.readthedocs.io/en/latest/site/api.html
The links on the download page however point to API v2: https://papermc.io/downloads

I guess API v2 is the current one that should be used? I'm asking since the "old" URLs like `https://papermc.io/ci/job/Paper-1.16/lastStableBuild/artifact/paperclip.jar` have stopped working, hence I'm looking for a future prove one now 🙂.

Btw, is there a way/URL that is redirected/rewritten to the latest version latest build automatically? Scripting a latest URL currently would requires:
1. Get latest version string from: https://papermc.io/api/v2/projects/paper
2. Get latest build number from: https://papermc.io/api/v2/projects/paper/versions/1.16.4
3. Forge download URL: `https://papermc.io/api/v2/projects/paper/versions/$version/builds/$build/downloads/paper-$version-$build.jar`

Possible, but of course `https://papermc.io/api/v2/projects/paper/versions/latest/builds/last/downloads/paper-latest-last.jar` would be great for scripting installs/updates easily.

**Comment by Prof-Bloodstone** [comment]
The API you are referring to that you used was Jenkins api and it was hidden because of tons of issues it caused (it very often didn't download latest jar).

The v1 api is deprecated and is going away at some point. The v2 api is what you should use, and there's not "latest" endpoint on purpose - to make it marginally harder to create auto-updaters. We know way too many people use them, based on the number of people that flood in when Paper releases builds that corrupt the worlds (only happened 3 times last year, but still).

**Comment by Proximyst** [comment]
You can find the documentation for API v2 on <https://papermc.io/api/docs>. Its repository is [https://github.com/PaperMC/bibliothek](_bibliothek_).

I'll keep this issue open as we need to update this repository with new info.

---

> because of tons of issues it caused (it very often didn't download latest jar).

This was actually intentional.

**Comment by Chew** [comment]
I was going to add a deprecation notice to the API page and suggest people go there. At some point, I would like to see more detailed documentation on the docs as well.

**Comment by Machine-Maker** [comment]
Do the docs really need to explain the v2 api? the swagger docs Are pretty self-explanatory. I would think just a link to the v2 docs would be enough. (along with the deprecation notice for v1)

**Comment by Pangamma** [comment]
If trying to retrofit multicraft, you can set up a PHP script that fetches the download URL and then returns that file's contents. It's a drop in replacement. 
https://pastebin.com/49JWgimu

**Comment by joshhsoj1902** [comment]
If anyone is looking for a bash/jq way of getting the latest, this seems to work (sorry for the awful format, I needed it all singleline)

It supports a "branch" being passed in (i.e. 1.16) and it'll find the latest version in that branch (i.e. 1.16.5). if that isn't needed the branch can be set to "latest". I haven't tested that bit yet, but if it doesn't work I'll come back and fix this comment.

```
ver=$branch \
 && if [[ $ver == "latest" ]]; then ver=`curl https://papermc.io/api/v2/projects/paper | jq -r '[.versions[] | match("^[0-9,.]*$").string ] | max_by(. | [splits("[.]")] | map(tonumber))'`; else ver=`curl https://papermc.io/api/v2/projects/paper | jq -r '[.versions[] | match("^'$ver'.*$").string ] | max_by(. | [splits("[.]")] | map(tonumber))'`; fi \
 && build=`curl https://papermc.io/api/v2/projects/paper/versions/$ver | jq '.builds | max_by(.)'` \
 && curl https://papermc.io/api/v2/projects/paper/versions/$ver/builds/$build/downloads/paper-$ver-$build.jar --output paper.jar
 ```

**Comment by MichaIng** [comment]
Pure bash for extracting the strings, although a little failsafe to changes, e.g. when the output changes from single line to multiple lines 😉:
```
local url='https://papermc.io/api/v2/projects/paper'
local version=$(curl -sSfL "$url"); version=${version%\"*} version=${version##*\"}
local build=$(curl -sSfL "$url/versions/$version"); build=${build%]*} build=${build##*[,[]}
#local file=$(curl -sSfL "$url/versions/$version/builds/$build"); file=${file##*\"name\":\"} file=${file%%\"*}
curl -sSfL "$url/versions/$version/builds/$build/downloads/paper-$version-$build.jar" -o /opt/papermc/paperclip.jar
```
As long as the file name pattern does not change, line 4 is obsolete.

**Comment by NatoBoram** [comment]
@joshhsoj1902's solution is a one-liner for no reason and @MichaIng's solution uses "local", which isn't allowed outside of function.

Here's my solution, which requires `jq`. Obtain it with `apt install jq` on Linux, `scoop install jq` on Windows, `brew install jq` on MacOS.

```
#!/bin/sh
version='1.17.1'
build=$(curl -s "https://papermc.io/api/v2/projects/paper/versions/$version" | jq -r '.builds[-1]')
download=$(curl -s "https://papermc.io/api/v2/projects/paper/versions/$version/builds/$build" | jq -r '.downloads.application.name')
curl -o paper.jar "https://papermc.io/api/v2/projects/paper/versions/$version/builds/$build/downloads/$download"
```

**Comment by joshhsoj1902** [comment]
@natoboram the existing scripts I was using needed it to be in a single line (which is what I said in my original comment). It wasn't for no reason...
