### ISSUE TITLE
Better explanation of per-world configs

### ISSUE THREAD

**Issue by sulu5890** [PaperMC/PaperDocs#72]
Currently per-world configs are described like this:

> World settings are configured on a per-world basis. The child-node default is used for all worlds that do not have their own specific settings.

While this description is sufficient for many, there are a good chunk of folks who don't understand how these settings work. Including something along the lines of [this pdf](https://www.spigotmc.org/attachments/per-world-guide-pdf.444348/) in the docs may be helpful.

**Comment by e-im** [comment]
Fixed in https://github.com/PaperMC/docs
